/* StructCap Timber — timber bridge assessment app (TIMBAR-style): bridge data, stringers, deck, substructure,
   vehicles, analysis, rating tables, report, and links to the repair-detail drawing workspace. */
(function (G) {
  'use strict';
  G.SC_TIMBER_UI = function (ctx) {
    const { T, esc, f, $, S, toast, isPro, COPY, logoMark, today, saveFile, render } = ctx;
    const TB = G.TIMBER, VIEW = 'timber', LS = 'sc.timber.v1';
    const store = { get() { try { return JSON.parse(localStorage.getItem(LS) || 'null'); } catch (e) { return null; } }, set(v) { try { localStorage.setItem(LS, JSON.stringify(v)); } catch (e) { } } };
    const A = { B: store.get() || TB.example3393(), R: null, stale: true, sel: 'bridge', rib: 'data', busy: false, hist: [], fut: [], open: { spans: true, sups: true, res: true } };
    const persist = () => store.set(A.B);
    const snap = () => { A.hist.push(JSON.stringify(A.B)); if (A.hist.length > 60) A.hist.shift(); A.fut = []; };
    const undo = redo => { const from = redo ? A.fut : A.hist, to = redo ? A.hist : A.fut; if (!from.length) return; to.push(JSON.stringify(A.B)); A.B = JSON.parse(from.pop()); A.stale = true; persist(); render(); };
    const VN = vid => (TB.vehicle(vid) || { n: vid }).n;
    const fmt = (v, d) => (v == null || !isFinite(v) ? '—' : f(v, d == null ? 2 : d));
    const pctCls = p => (!isFinite(p) ? '' : p < 100 ? 'bad' : p < 110 ? 'warn' : 'ok');
    const vids = () => TB.VEH_ORDER.filter(k => TB.vehOn(A.B, k));

    // ------------------------------------------------------------------ bridge editing helpers
    function setPath(path, v) { const ks = path.split('.'); let o = A.B; for (let i = 0; i < ks.length - 1; i++) { if (o[ks[i]] == null) o[ks[i]] = /^\d+$/.test(ks[i + 1]) ? [] : {}; o = o[ks[i]]; } o[ks[ks.length - 1]] = v; }
    function getPath(path) { return path.split('.').reduce((o, k) => (o == null ? undefined : o[k]), A.B); }
    function setSpans(n) {
      n = Math.max(1, Math.min(24, n | 0)); const B = A.B, tpl = B.spans[B.spans.length - 1] || TB.newBridge().spans[0];
      while (B.spans.length < n) B.spans.push(JSON.parse(JSON.stringify(tpl)));
      B.spans.length = n; const st = B.supports || []; const supT = st[st.length - 2] || st[0] || TB.newBridge().supports[1];
      while (st.length < n + 1) st.splice(st.length - 1, 0, JSON.parse(JSON.stringify(supT)));
      st.length = n + 1; st.forEach((s, k) => { s.kind = k === 0 || k === n ? 'abut' : 'pier'; }); B.supports = st;
    }
    function setStringers(si, n) { const S = A.B.spans[si]; n = Math.max(1, Math.min(20, n | 0)); const last = S.stringers[S.stringers.length - 1]; while (S.stringers.length < n) S.stringers.push(JSON.parse(JSON.stringify(last))); S.stringers.length = n; const sp = S.spacing || []; while (sp.length < n + 1) sp.splice(sp.length - 1, 0, 1.0); sp.length = n + 1; S.spacing = sp; }
    const supName = k => (k === 0 ? T('Abutment 1', 'ตอม่อริม 1') : k === A.B.spans.length ? T('Abutment 2', 'ตอม่อริม 2') : T('Pier ', 'ตอม่อกลาง ') + k);

    // ------------------------------------------------------------------ ribbon
    const IC = { new: '<path d="M6 3h8l4 4v14H6zM14 3v4h4M12 10v7M8.5 13.5h7"/>', open: '<path d="M3 7h6l2 2h10v10H3zM3 11h18"/>', save: '<path d="M5 3h12l3 3v15H5zM8 3v5h8V3M8 14h8v7H8z"/>', ex: '<path d="M4 20V9l8-5 8 5v11M9 20v-6h6v6"/>', run: '<path d="M7 4l13 8-13 8z"/>', rep: '<path d="M6 3h12v18H6zM9 8h6M9 12h6M9 16h4"/>', undo: '<path d="M9 7L4 12l5 5M4 12h11a5 5 0 0 1 0 10h-3"/>', redo: '<path d="M15 7l5 5-5 5M20 12H9a5 5 0 0 0 0 10h3"/>', span: '<path d="M2 9h20M4 9v10M20 9v10M12 9v10"/>', str: '<path d="M3 8h18M3 12h18M3 16h18"/>', pile: '<path d="M7 4v17M17 4v17M4 4h16"/>', veh: '<path d="M3 15h18v3H3zM5 15l2-6h8l3 6M7 21a2 2 0 1 0 0-.1M17 21a2 2 0 1 0 0-.1"/>', draw: '<path d="M4 20l4-1 11-11-3-3L5 16zM14 6l3 3"/>', res: '<path d="M3 20h18M5 20V10M9 20V6M13 20v-8M17 20V4"/>' };
    const icon = (k, big) => `<svg class="an-ic ${big ? 'big' : ''}" viewBox="0 0 24 24" aria-hidden="true">${IC[k] || IC.span}</svg>`;
    function RIB() {
      return [
        ['file', T('File', 'ไฟล์'), [[T('Bridge file', 'ไฟล์สะพาน'), [{ c: 'new', i: 'new', l: T('New bridge', 'สะพานใหม่') }, { file: 1, i: 'open', l: T('Open', 'เปิด') }, { c: 'save', i: 'save', l: T('Save', 'บันทึก') }, { c: 'ex', i: 'ex', l: T('Example: Bridge 3393', 'ตัวอย่าง: สะพาน 3393') }]], [T('Edit', 'แก้ไข'), [{ col: [{ c: 'undo', i: 'undo', l: T('Undo', 'เลิกทำ') }, { c: 'redo', i: 'redo', l: T('Redo', 'ทำซ้ำ') }] }]]]],
        ['data', T('Bridge data', 'ข้อมูลสะพาน'), [[T('Bridge', 'สะพาน'), [{ c: 'sel', v: 'bridge', i: 'ex', l: T('Bridge info', 'ข้อมูลสะพาน') }, { c: 'sel', v: 'span:0', i: 'span', l: T('Spans & deck', 'ช่วงและพื้น') }, { c: 'sel', v: 'str:0', i: 'str', l: T('Stringers', 'คานไม้') }, { c: 'sel', v: 'sup:' + (A.B.spans.length > 1 ? 1 : 0), i: 'pile', l: T('Piers & abutments', 'ตอม่อ') }, { c: 'sel', v: 'veh', i: 'veh', l: T('Vehicles', 'ยานพาหนะ') }]]]],
        ['analyse', T('Analyse', 'วิเคราะห์'), [[T('Load rating', 'ประเมินกำลังรับน้ำหนัก'), [{ c: 'run', i: 'run', l: A.busy ? T('Analysing…', 'กำลังวิเคราะห์…') : T('Analyse & rate', 'วิเคราะห์และประเมิน') }, { c: 'sel', v: 'res', i: 'res', l: T('Results summary', 'สรุปผล') }]], [T('Output', 'ผลลัพธ์'), [{ c: 'report', i: 'rep', l: T('Report', 'รายงาน') }, { c: 'draw', i: 'draw', l: T('Repair drawings', 'แบบซ่อม') }]]]]
      ];
    }
    function rbtn(it, big) { const lab = esc(it.l); if (it.file) return `<label class="an-rb ${big ? 'big' : 'sm'}" title="${lab}">${icon(it.i, big)}<span>${lab}</span><input type="file" accept=".json,application/json" id="tb-file" hidden></label>`; return `<button class="an-rb ${big ? 'big' : 'sm'} ${it.c === 'run' ? 'cn-hot' : ''}" data-act="tb-rb" data-c="${it.c}" ${it.v ? `data-v="${esc(it.v)}"` : ''} aria-pressed="${it.v && A.sel === it.v}" title="${lab}" ${it.c === 'run' && A.busy ? 'disabled' : ''}>${icon(it.i, big)}<span>${lab}</span></button>`; }
    function ribHTML() { const tabs = RIB(), cur = tabs.find(t => t[0] === A.rib) || tabs[1]; return `<div class="an-rib" id="tbRib"><div class="an-ribtabs" role="tablist">${tabs.map(t => `<button role="tab" class="an-rtab" data-act="tb-ribtab" data-t="${t[0]}" aria-selected="${t[0] === cur[0]}">${t[1]}</button>`).join('')}<span class="grow"></span><span class="an-qat">${[['undo', 'undo', T('Undo', 'เลิกทำ')], ['redo', 'redo', T('Redo', 'ทำซ้ำ')], ['save', 'save', T('Save', 'บันทึก')], ['run', 'run', T('Analyse', 'วิเคราะห์')]].map(([c, i, l]) => `<button class="an-qb ${c === 'run' ? 'hot' : ''}" data-act="tb-rb" data-c="${c}" title="${esc(l)}" aria-label="${esc(l)}">${icon(i)}</button>`).join('')}</span></div><div class="an-ribbar" role="toolbar">${cur[2].map(([title, items]) => `<div class="an-rg"><div class="an-rgi">${items.map(it => (it.col ? `<div class="an-rcol">${it.col.map(x => rbtn(x, false)).join('')}</div>` : rbtn(it, true))).join('')}</div><div class="an-rgt">${title}</div></div>`).join('')}</div></div>`; }
    const ribRefresh = () => { const r = $('#tbRib'); if (r) r.outerHTML = ribHTML(); };

    // ------------------------------------------------------------------ tree
    function tn(key, label, extra, kids, openKey) { const on = A.sel === key, open = openKey ? A.open[openKey] : true; return `<li>${kids != null && openKey ? `<button class="cn-tw" data-act="tb-tog" data-k="${openKey}" aria-expanded="${open}">${open ? '▾' : '▸'}</button>` : ''}<button class="an-tl2 cn-tl ${on ? 'on' : ''}" data-act="tb-sel" data-k="${esc(key)}"><span class="an-tlt">${label}</span>${extra || ''}</button>${kids != null && open ? `<ul>${kids}</ul>` : ''}</li>`; }
    const tag = p => (isFinite(p) ? `<span class="cn-u ${pctCls(p)}">${f(p, 0)}%</span>` : '');
    function treeHTML() {
      const B = A.B, R = A.R && !A.stale ? A.R : null;
      const spans = B.spans.map((S, i) => { const sp = R && R.spans[i]; const t44 = sp ? Math.min(...sp.str.map(s => (s.veh.T44 && s.veh.T44.pct) || Infinity)) : NaN;
        return tn('span:' + i, T('Span ', 'ช่วง ') + (i + 1) + ' · ' + f(+S.L, 2) + ' m' + (S.rate === false ? ' <i class="muted">(' + T('not rated', 'ไม่ประเมิน') + ')</i>' : ''), tag(t44), tn('str:' + i, T('Stringers', 'คานไม้') + ' (' + S.stringers.length + ')') + tn('patch:' + i, T('Patch loads', 'น้ำหนักแผ่') + ' (' + (S.patches || []).length + ')') + tn('plank:' + i, T('Deck planks', 'แผ่นพื้นไม้')), null); }).join('');
      const sups = (B.supports || []).map((Su, k) => { const su = R && R.supports[k]; const t44 = su ? Math.min(...su.piles.map(p => (p.veh.T44 && p.veh.T44.t / 44.04 * 100) || Infinity)) : NaN; return tn('sup:' + k, supName(k) + ' · ' + (Su.piles || []).length + ' ' + T('piles', 'เสาเข็ม'), tag(t44), null); }).join('');
      const res = R ? tn('res', T('Summary', 'สรุป'), '') + R.spans.map((sp, i) => (sp ? tn('rs:' + i, T('Span ', 'ช่วง ') + (i + 1) + T(' stringers', ' คานไม้'), '') : '')).join('') + R.supports.map((su, k) => (su ? tn('ru:' + k, su.name, '') : '')).join('') + tn('repairs', T('Repair details', 'รายละเอียดการซ่อม'), R.summary.low.length ? `<span class="cn-u bad">${R.summary.low.length}</span>` : '') : `<li class="muted small tb-tip">${A.stale && A.R ? T('Data changed — analyse again.', 'ข้อมูลเปลี่ยน — วิเคราะห์ใหม่') : T('Press Analyse & rate.', 'กด วิเคราะห์และประเมิน')}</li>`;
      return `<div class="an-wtree cn-tree"><ul class="an-wt">${tn('bridge', '<b>' + esc(B.no || '') + '</b> ' + esc(B.name || ''), '')}${tn('spans', T('Superstructure', 'โครงสร้างส่วนบน'), '', spans, 'spans')}${tn('sups', T('Substructure', 'โครงสร้างส่วนล่าง'), '', sups, 'sups')}${tn('veh', T('Vehicles', 'ยานพาหนะ'), '<span class="muted small">' + vids().length + '</span>')}${tn('resh', T('Results', 'ผลลัพธ์'), '', res, 'res')}</ul></div>`;
    }

    // ------------------------------------------------------------------ input widgets
    const inp = (path, val, o) => { o = o || {}; const v = val === undefined ? getPath(path) : val; if (o.sel) return `<select data-tb="${esc(path)}" ${o.num ? 'data-num="1"' : ''}>${o.sel.map(q => `<option value="${esc(q[0])}" ${String(q[0]) === String(v) ? 'selected' : ''}>${esc(q[1])}</option>`).join('')}</select>`; if (o.chk) return `<input type="checkbox" data-tb="${esc(path)}" data-chk="1" ${v ? 'checked' : ''}>`; return `<input ${o.num ? 'type="number" step="any" data-num="1"' : ''} data-tb="${esc(path)}" value="${esc(v == null ? '' : v)}" ${o.w ? `style="width:${o.w}px"` : ''}>`; };
    const fld = (path, lbl, o, unit) => `<label class="cn-f"><span>${lbl}${unit ? ` <i>${unit}</i>` : ''}</span>${inp(path, undefined, o)}</label>`;
    const MATS = [['jarrah', 'Jarrah'], ['wandoo', 'Wandoo'], ['wjE', 'Wandoo (Jarrah E)'], ['karri', 'Karri'], ['marri', 'Marri'], ['steel', T('Steel', 'เหล็ก')]];
    const GRS = Object.keys(TB.GRADES).map(g => [g, g]), CONDS = [['G', T('G — good', 'G — ดี')], ['F', T('F — friable', 'F — เปราะ')], ['R', T('R — rot', 'R — ผุ')]];
    const DEFS = [[0, T('0 none', '0 ไม่มี')], [1, T('1 pipe', '1 โพรงกลม')], [1.5, T('1.5 ellipse', '1.5 วงรี')], [2, T('2 U-shape', '2 รูปตัว U')]];
    const STEELS = ['410UB54', '410UB60', '360UB57', '460UB67', '530UB82', '310UC97', '250UC73'].map(s => [s, s]);

    function panelHTML() {
      const B = A.B, k = A.sel, head = (t, sub) => `<div class="cn-ph"><b>${t}</b>${sub ? `<span class="muted small">${sub}</span>` : ''}</div>`;
      if (k === 'bridge') return head(T('Bridge information', 'ข้อมูลสะพาน'), T('MRWA practice: working stress (AS 1720.1-1988), k1 by road type, live load × (1 + DLA)', 'แนวทาง MRWA: หน่วยแรงใช้งาน (AS 1720.1-1988), k1 ตามประเภทถนน, น้ำหนักจร × (1 + DLA)')) + `<div class="tb-form">` +
        fld('no', T('Bridge number', 'หมายเลขสะพาน')) + fld('name', T('Name / road', 'ชื่อ / ถนน')) + fld('designer', T('Assessed by', 'ผู้ประเมิน')) + fld('road', T('Road type (k1)', 'ประเภทถนน (k1)'), { sel: [['local', T('Local road — k1 = 1.65', 'ถนนท้องถิ่น — k1 = 1.65')], ['main', T('Main road (> 500 veh/day) — k1 = 1.40', 'ถนนสายหลัก (> 500 คัน/วัน) — k1 = 1.40')]] }) +
        `<label class="cn-f"><span>${T('Number of spans', 'จำนวนช่วง')}</span><input type="number" min="1" max="24" data-tbspans="1" value="${B.spans.length}"></label>` +
        fld('soil.gamma', T('Soil unit weight γ', 'หน่วยน้ำหนักดิน γ'), { num: 1 }, 'kN/m³') + fld('soil.ka', T('Active pressure coefficient Ka', 'สัมประสิทธิ์แรงดันดิน Ka'), { num: 1 }) + fld('soil.sur', T('Vehicle surcharge height', 'ความสูงดินถมแทนน้ำหนักจร'), { num: 1 }, 'm') + `</div>` +
        `<p class="cn-note">${T('Each span is analysed as a simply supported grillage: stringers on effective span Le = (L + Lo)/2 with the deck planks (or concrete overlay) as transverse members. Vehicles are stepped along and across the carriageway; stringers, piles, halfcaps, halfcap bearing, deck planks and wing wall piles are rated in tonnes and % of T44 / M1600.', 'แต่ละช่วงวิเคราะห์เป็นกริลเลจช่วงเดี่ยว คานบนช่วงประสิทธิผล Le = (L + Lo)/2 โดยมีแผ่นพื้น (หรือคอนกรีตทับหน้า) เป็นชิ้นส่วนตามขวาง เลื่อนยานพาหนะตามยาวและตามขวาง แล้วประเมินคาน เสาเข็ม คานหัวเสา การรับแรงแบก แผ่นพื้น และเสาเข็มกำแพงปีก เป็นตันและ % ของ T44 / M1600')}</p>`;
      if (k === 'veh') { return head(T('Rating vehicles', 'ยานพาหนะประเมิน'), T('TIMBAR standard vehicles (App A); untick vehicles that do not fit the carriageway or are not required. M1600 is not normally checked (tick it to include); the wide models 2 / 3 are optional.', 'ยานพาหนะมาตรฐาน TIMBAR; เอาเครื่องหมายออกหากไม่ต้องการ M1600 ไม่ตรวจโดยปกติ (เลือกเพื่อรวม) รุ่นกว้าง 2 / 3 เลือกได้')) +
        `<div class="cn-tbl"><table><thead><tr><th></th><th>${T('Vehicle', 'ยานพาหนะ')}</th><th class="num">${T('Rating weight', 'น้ำหนักประเมิน')} (t)</th><th class="num">${T('Grillage load', 'น้ำหนักในกริลเลจ')} (kN)</th><th class="num">DLA</th><th class="num">${T('Axle width', 'ระยะล้อ')} (m)</th><th class="num">${T('Side clearance', 'ระยะข้าง')} (m)</th></tr></thead><tbody>${TB.VEH_ORDER.map((v, n) => { const q = TB.vehicle(v); return `${q.opt && !TB.vehicle(TB.VEH_ORDER[n - 1]).opt ? `<tr class="cn-grp"><td colspan="7">${T('Optional: wider triaxle / quad models 2 and 3 (multi-wheel axles)', 'เลือกได้: ไตรแอกเซิล / ควอด รุ่นกว้าง 2 และ 3 (เพลาหลายล้อ)')}</td></tr>` : ''}<tr><td><input type="checkbox" data-tbveh="${v}" ${TB.vehOn(B, v) ? 'checked' : ''}></td><td><b>${q.n}</b>${q.pm ? ` <span class="muted small">+ ${T('prime mover', 'หัวลาก')}</span>` : ''}</td><td class="num">${f(q.W, 2)}</td><td class="num">${f(q.Wk, 0)}${q.udl ? ' + ' + q.udl + ' kN/m' : ''}</td><td class="num">${f(q.dla, 2)}</td><td class="num">${f(q.width, 1)}</td><td class="num">${f(q.side, 2)}</td></tr>`; }).join('')}</tbody></table></div>` +
        fld('veh.t44A', T('T44 axle spacing A (0 = all models 3–8 m)', 'ระยะเพลา T44 A (0 = ทุกแบบ 3–8 ม.)'), { num: 1 }, 'm') + `<p class="cn-note">${T('Two T44 side by side carry 0.9 each and two M1600 carry 1.0 + 0.8, on the deck and on the piles and halfcaps. M1600 includes the 6 kN/m lane load everywhere. Tandem, triaxle and quad groups always run with their prime mover (6 t steer + 16.5 t drive) whenever it is on the bridge; the rating weight is the axle group only. HLP vehicles stay within ±1.0 m of the carriageway centreline.', 'T44 สองคันคูณ 0.9 และ M1600 สองคัน 1.0 + 0.8 ทั้งพื้น เสาเข็ม และคานหัวเสา M1600 รวมน้ำหนักแผ่ 6 kN/m ทุกส่วน กลุ่มเพลาแทนเดม ไตรแอกเซิล ควอด วิ่งพร้อมหัวลาก (6 + 16.5 ตัน) เมื่ออยู่บนสะพาน น้ำหนักประเมินคิดเฉพาะกลุ่มเพลา HLP อยู่ในระยะ ±1.0 ม. จากกึ่งกลาง')}</p>`; }
      if (k.startsWith('span:')) { const i = +k.slice(5), Sp = B.spans[i], gm = (() => { try { return TB.spanGeom(B, i); } catch (e) { return null; } })(); return head(T('Span ', 'ช่วง ') + (i + 1), gm ? 'Le = ' + f(gm.Le, 3) + ' m · ' + T('carriageway', 'ช่องจราจร') + ' ' + f(gm.cw1 - gm.cw0, 2) + ' m' : '') + `<div class="tb-form">` +
        fld('spans.' + i + '.rate', T('Rate this span', 'ประเมินช่วงนี้'), { chk: 1 }) + fld('spans.' + i + '.L', T('Span L (centre to centre of supports)', 'ช่วง L (ศูนย์กลางถึงศูนย์กลาง)'), { num: 1 }, 'm') + fld('spans.' + i + '.Lo', T('Clear span Lo (0 = default)', 'ช่วงว่าง Lo (0 = ค่าเริ่มต้น)'), { num: 1 }, 'm') + fld('spans.' + i + '.ndiv', T('Stringer divisions (even)', 'จำนวนแบ่งคาน (คู่)'), { num: 1 }) +
        fld('spans.' + i + '.width', T('Overall deck width', 'ความกว้างพื้นทั้งหมด'), { num: 1 }, 'm') + fld('spans.' + i + '.kerbL', T('Kerb / offset LHS', 'ขอบทาง ซ้าย'), { num: 1 }, 'm') + fld('spans.' + i + '.kerbR', T('Kerb / offset RHS', 'ขอบทาง ขวา'), { num: 1 }, 'm') +
        fld('spans.' + i + '.deck.t', T('Transverse member thickness', 'ความหนาชิ้นส่วนตามขวาง'), { num: 1 }, 'm') + fld('spans.' + i + '.deck.E', T('Transverse E (7900 timber, 35000 concrete)', 'E ตามขวาง (ไม้ 7900, คอนกรีต 35000)'), { num: 1 }, 'MPa') + fld('spans.' + i + '.deck.gamma', T('Transverse unit weight', 'หน่วยน้ำหนักตามขวาง'), { num: 1 }, 'kN/m³') + `</div>` +
        `<h4 class="cn-h4">${T('Stringer spacing (deck edge → S1, S1 → S2, …, Sn → deck edge)', 'ระยะคาน (ขอบพื้น → S1, S1 → S2, …, Sn → ขอบพื้น)')}</h4><div class="tb-spc">${(Sp.spacing || []).map((v, j) => `<label><span>${j === 0 ? T('edge→S1', 'ขอบ→S1') : j === Sp.spacing.length - 1 ? 'S' + j + T('→edge', '→ขอบ') : 'S' + j + '→S' + (j + 1)}</span>${inp('spans.' + i + '.spacing.' + j, v, { num: 1, w: 70 })}</label>`).join('')}</div>` +
        `<div class="cn-btns"><button class="btn btn-ghost xs" data-act="tb-rb" data-c="strn" data-v="${i}:1">+ ${T('stringer', 'คาน')}</button><button class="btn btn-ghost xs" data-act="tb-rb" data-c="strn" data-v="${i}:-1">− ${T('stringer', 'คาน')}</button><button class="btn btn-ghost xs" data-act="tb-rb" data-c="copyspan" data-v="${i}">${T('Apply this span to all spans', 'ใช้ข้อมูลช่วงนี้กับทุกช่วง')}</button></div>`; }
      if (k.startsWith('str:')) { const i = +k.slice(4), Sp = B.spans[i]; const rows = Sp.stringers.map((s, j) => {
          const steel = s.mat === 'steel', stn = ['e1', 'mid', 'e2'];
          const head = `<tr class="cn-grp"><td colspan="15"><b>S${j + 1}</b> ${inp('spans.' + i + '.stringers.' + j + '.mat', s.mat || 'jarrah', { sel: MATS })} ${steel ? inp('spans.' + i + '.stringers.' + j + '.steel', s.steel || '410UB54', { sel: STEELS }) + ' ' + inp('spans.' + i + '.stringers.' + j + '.steelGrade', s.steelGrade || 250, { sel: [[250, 'Gr 250'], [300, 'Gr 300']] }) : inp('spans.' + i + '.stringers.' + j + '.grade', s.grade || (TB.SPECIES[s.mat || 'jarrah'] || {}).stringer || 'F17', { sel: GRS })}</td></tr>`;
          if (steel) return head;
          return head + stn.map(st => { const p = 'spans.' + i + '.stringers.' + j + '.' + st, q = s[st] || {}, sec = (() => { try { return TB.stringerSection(q, st !== 'mid'); } catch (e) { return null; } })();
            return `<tr><td>${{ e1: T('End 1', 'ปลาย 1'), mid: T('Mid', 'กลาง'), e2: T('End 2', 'ปลาย 2') }[st]}</td>${['W', 'H', 'V'].map(c => `<td>${inp(p + '.' + c, q[c], { num: 1, w: 58 })}</td>`).join('')}<td>${st === 'mid' ? `<span class="muted">${sec ? f(sec.F, 3) : ''}</span>` : inp(p + '.F', q.F || '', { num: 1, w: 52 })}</td><td>${inp(p + '.def', q.def || 0, { sel: DEFS, num: 1 })}</td><td>${inp(p + '.' + (+q.def === 1 ? 'R' : 'Vs'), +q.def === 1 ? q.R : q.Vs, { num: 1, w: 50 })}</td><td>${inp(p + '.L', q.L, { num: 1, w: 50 })}</td><td>${inp(p + '.Rr', q.Rr, { num: 1, w: 50 })}</td><td>${inp(p + '.Ts', q.Ts, { num: 1, w: 50 })}</td><td>${inp(p + '.cond', q.cond || 'G', { sel: CONDS })}</td><td class="num" id="tbA-${i}-${j}-${st}">${sec ? f(st === 'mid' ? sec.Ag / 1e5 : sec.A / 1e5, 3) : '—'}</td><td class="num" id="tbI-${i}-${j}-${st}">${sec ? f(sec.I / 1e9, 3) : '—'}</td><td class="num" id="tbY-${i}-${j}-${st}">${sec && st === 'mid' ? f(sec.ymax, 1) : ''}</td><td>${sec ? secSVG(sec) : ''}</td></tr>`; }).join(''); }).join('');
        return head(T('Stringers — span ', 'คานไม้ — ช่วง ') + (i + 1), T('W top-cut width (999 = square sawn), H horizontal, V vertical (mm); defect: 1 pipe radius R, 1.5/2 solid timber below (Vs), left (L), right (R), top (T, 1.5)', 'W ความกว้างรอยตัดบน (999 = ไม้เลื่อย), H แนวนอน, V แนวตั้ง (มม.); ตำหนิ: 1 รัศมีโพรง R, 1.5/2 เนื้อไม้ดีด้านล่าง ซ้าย ขวา บน')) +
          `<div class="cn-tbl tb-str"><table><thead><tr><th></th><th>W</th><th>H</th><th>V</th><th>${T('Oval F', 'ค่ารี F')}</th><th>${T('Defect', 'ตำหนิ')}</th><th>R / Vs</th><th>L</th><th>R</th><th>T</th><th>${T('Cond.', 'สภาพ')}</th><th class="num">A ×10⁵</th><th class="num">I ×10⁹</th><th class="num">y<sub>max</sub></th><th></th></tr></thead><tbody>${rows}</tbody></table></div><p class="cn-note">${T('A = net area with bottom cut at the ends (shear), gross area at midspan; I about the net centroid with the round bottom. Rot / friable timber is excluded from the section; the condition reduces permissible stresses (friable 85/70/70 %, rot 15/10/10 %).', 'A = พื้นที่สุทธิที่ปลาย (เฉือน), พื้นที่รวมกลางช่วง; I รอบแกนสะเทินของหน้าตัดสุทธิ ไม้ผุ/เปราะไม่นับในหน้าตัด และลดหน่วยแรงที่ยอมให้ตามสภาพ')}</p>`; }
      if (k.startsWith('patch:')) { const i = +k.slice(6), P = B.spans[i].patches || []; return head(T('Patch (dead) loads — span ', 'น้ำหนักบรรทุกคงที่แบบแผ่ — ช่วง ') + (i + 1), T('Trapezoidal patches: thickness at the corners A2R, A1R, A2L, A1L; X along the span from support 1, Y across from the LHS deck edge. Stringer and deck self weight is automatic.', 'แผ่นสี่เหลี่ยมคางหมู: ความหนาที่มุม A2R, A1R, A2L, A1L; X ตามช่วงจากจุดรองรับ 1, Y ตามขวางจากขอบซ้าย น้ำหนักคานและพื้นคำนวณอัตโนมัติ')) +
        `<div class="cn-tbl"><table><thead><tr><th>${T('Name', 'ชื่อ')}</th><th>γ (kN/m³)</th><th>X</th><th>Y</th><th>${T('Length X', 'ยาว X')}</th><th>${T('Width Y', 'กว้าง Y')}</th><th>t A2R</th><th>t A1R</th><th>t A2L</th><th>t A1L</th><th></th></tr></thead><tbody>${P.map((q, j) => { const p = 'spans.' + i + '.patches.' + j; return `<tr><td>${inp(p + '.name', q.name, { w: 120 })}</td>${['gamma', 'x', 'y', 'lx', 'ly'].map(c => `<td>${inp(p + '.' + c, q[c], { num: 1, w: 56 })}</td>`).join('')}${[0, 1, 2, 3].map(c => `<td>${inp(p + '.t.' + c, (q.t || [])[c], { num: 1, w: 52 })}</td>`).join('')}<td><button class="btn btn-ghost xs" data-act="tb-rb" data-c="patchdel" data-v="${i}:${j}">✕</button></td></tr>`; }).join('')}</tbody></table></div><div class="cn-btns"><button class="btn btn-ghost xs" data-act="tb-rb" data-c="patchadd" data-v="${i}">+ ${T('Patch load', 'น้ำหนักแผ่')}</button><button class="btn btn-ghost xs" data-act="tb-rb" data-c="kerbcalc" data-v="${i}">${T('Kerb + guardrail helper', 'ตัวช่วยขอบทาง + ราวกั้น')}</button></div><p class="cn-note">${T('Guardrail line loads: 0.3 kN/m W-beam or timber, 0.5 with top rail, 1.0 heavier. Kerb + guardrail as one patch: t = (rail + kerb weight) / γ / kerb width. Pavement 22 kN/m³.', 'ราวกั้น: 0.3 kN/m (W-beam/ไม้), 0.5 มีราวบน, 1.0 แบบหนัก; ขอบทาง + ราว รวมเป็นแผ่นเดียว t = (ราว + น้ำหนักขอบทาง)/γ/ความกว้าง; ผิวทาง 22 kN/m³')}</p>`; }
      if (k.startsWith('plank:')) { const i = +k.slice(6), p = 'spans.' + i + '.planks.'; return head(T('Deck planks — span ', 'แผ่นพื้นไม้ — ช่วง ') + (i + 1), T('Continuous beam over the stringers under two wheel patches 1.8 m apart (200 × 400 mm, 45° spread through the paving)', 'คานต่อเนื่องบนคาน รับล้อสองล้อห่าง 1.8 ม. (200 × 400 มม. กระจาย 45° ผ่านผิวทาง)')) + `<div class="tb-form">` +
        fld(p + 'on', T('Rate deck planks', 'ประเมินแผ่นพื้น'), { chk: 1 }) + fld(p + 'b', T('Plank width', 'ความกว้างแผ่น'), { num: 1 }, 'mm') + fld(p + 'd', T('Plank depth', 'ความหนาแผ่น'), { num: 1 }, 'mm') + fld(p + 'rot', T('Loss of depth (rot)', 'ความหนาที่สูญเสีย (ผุ)'), { num: 1 }, '%') + fld(p + 'pave', T('Pavement depth', 'ความหนาผิวทาง'), { num: 1 }, 'm') + fld(p + 'topCut', T('Stringer top-cut width', 'ความกว้างรอยตัดบนคาน'), { num: 1 }, 'mm') + fld(p + 'mat', T('Species', 'ชนิดไม้'), { sel: MATS.slice(0, 5) }) + fld(p + 'grade', T('Grade', 'ชั้นคุณภาพ'), { sel: GRS }) + fld(p + 'cond', T('Condition', 'สภาพ'), { sel: CONDS.slice(0, 2) }) + `</div>`; }
      if (k.startsWith('sup:')) { const kk = +k.slice(4), Su = B.supports[kk], abut = kk === 0 || kk === B.spans.length, base = 'supports.' + kk + '.';
        const cols = [['id', '#', 36], ['x', T('x from LHS (m)', 'x จากซ้าย (ม.)'), 62], ['d', 'D (mm)', 56], ['def', T('Defect', 'ตำหนิ'), 0], ['r', 'r', 46], ['L', 'L', 46], ['R', 'R', 46], ['B', 'B', 46], ['F', 'F', 46], ['cond', T('Cond.', 'สภาพ'), 0], ['grade', T('Grade', 'ชั้น'), 0], ['Hgl', T('H to GL (m)', 'สูงถึงดิน (ม.)'), 52], ['dfix', T('Fixity (m)', 'จุดยึด (ม.)'), 48], ['e', 'e (m)', 52], ['dc', T('Crit. depth (m)', 'ระดับวิกฤต (ม.)'), 52], ['bearT', T('Bearing (mm)', 'แรงแบก (มม.)'), 50], ['bearS', T('Steel bearing (mm)', 'แบกเหล็ก (มม.)'), 50], ['mat', T('Species', 'ชนิดไม้'), 0]].concat(abut ? [['hr', T('Road→cap (m)', 'ผิวทาง→หัวเสา (ม.)'), 52], ['ds', T('Sheeting (m)', 'แผ่นกันดิน (ม.)'), 48], ['osw', T('Outside width (m)', 'ระยะนอก (ม.)'), 48]] : []);
        const piles = (Su.piles || []).map((pl, j) => `<tr>${cols.map(([c, , w]) => `<td>${c === 'def' ? inp(base + 'piles.' + j + '.def', pl.def || 0, { sel: [[0, '0'], [1, '1 pipe'], [2, '2 ellipse']], num: 1 }) : c === 'cond' ? inp(base + 'piles.' + j + '.cond', pl.cond || 'G', { sel: CONDS }) : c === 'grade' ? inp(base + 'piles.' + j + '.grade', pl.grade || (TB.SPECIES[pl.mat || 'jarrah'] || {}).pile || 'F17', { sel: GRS }) : c === 'mat' ? inp(base + 'piles.' + j + '.mat', pl.mat || 'jarrah', { sel: MATS.slice(0, 5) }) : inp(base + 'piles.' + j + '.' + c, pl[c] != null ? pl[c] : '', { num: c !== 'id', w })}</td>`).join('')}<td><button class="btn btn-ghost xs" data-act="tb-rb" data-c="piledel" data-v="${kk}:${j}">✕</button></td></tr>`).join('');
        const wings = (Su.wing || []).map((w, wi) => `<div class="tb-wing"><div class="tb-form">${fld(base + 'wing.' + wi + '.name', T('Wing wall', 'กำแพงปีก'))}${fld(base + 'wing.' + wi + '.phi', 'φ (°)', { num: 1 })}${fld(base + 'wing.' + wi + '.alpha', T('Angle to road α (°)', 'มุมกับถนน α (°)'), { num: 1 })}${fld(base + 'wing.' + wi + '.slope', T('Batter 1 : x', 'ลาดเอียง 1 : x'), { num: 1 })}${fld(base + 'wing.' + wi + '.passive', T('Passive pressure', 'แรงดันดินต้าน'), { chk: 1 })}${fld(base + 'wing.' + wi + '.osw', T('Outside support width', 'ระยะรองรับนอก'), { num: 1 }, 'm')}</div>
          <div class="cn-tbl"><table><thead><tr><th>#</th><th>${T('Height (m)', 'ความสูง (ม.)')}</th><th>${T('Spacing (m)', 'ระยะ (ม.)')}</th><th>D</th><th>${T('Defect', 'ตำหนิ')}</th><th>r</th><th>L</th><th>R</th><th>B</th><th>F</th><th>${T('Cond.', 'สภาพ')}</th><th>${T('Crit. (m)', 'วิกฤต (ม.)')}</th><th title="${T('Top of the live-load surcharge above GL (blank: edge pile at its height, others none; −1 = none)', 'ระดับบนของดินถมแทนน้ำหนักจรเหนือดิน')}">${T('LL surcharge top (m)', 'ระดับดินถมแทน LL (ม.)')}</th><th></th></tr></thead><tbody>${(w.piles || []).map((pl, j) => { const q = base + 'wing.' + wi + '.piles.' + j + '.'; return `<tr><td>${inp(q + 'id', pl.id, { w: 36 })}</td><td>${inp(q + 'h', pl.h, { num: 1, w: 52 })}</td><td>${inp(q + 's', pl.s, { num: 1, w: 52 })}</td><td>${inp(q + 'd', pl.d, { num: 1, w: 52 })}</td><td>${inp(q + 'def', pl.def || 0, { sel: [[0, '0'], [1, '1'], [2, '2']], num: 1 })}</td>${['r', 'L', 'R', 'B', 'F'].map(c => `<td>${inp(q + c, pl[c], { num: 1, w: 44 })}</td>`).join('')}<td>${inp(q + 'cond', pl.cond || 'G', { sel: CONDS })}</td><td>${inp(q + 'dc', pl.dc != null ? pl.dc : 1, { num: 1, w: 46 })}</td><td>${inp(q + 'sur', pl.sur != null ? pl.sur : '', { num: 1, w: 50 })}</td><td><button class="btn btn-ghost xs" data-act="tb-rb" data-c="wpdel" data-v="${kk}:${wi}:${j}">✕</button></td></tr>`; }).join('')}</tbody></table></div><div class="cn-btns"><button class="btn btn-ghost xs" data-act="tb-rb" data-c="wpadd" data-v="${kk}:${wi}">+ ${T('pile', 'เสาเข็ม')}</button><button class="btn btn-ghost xs" data-act="tb-rb" data-c="wdel" data-v="${kk}:${wi}">${T('Delete wing wall', 'ลบกำแพงปีก')}</button></div></div>`).join('');
        return head(supName(kk), abut ? T('Abutment piles: propped cantilevers with soil pressure (Ka γ), surcharge and eccentric bearing', 'เสาเข็มตอม่อริม: คานยื่นค้ำปลาย รับแรงดันดินและน้ำหนักเยื้องศูนย์') : T('Pier piles: propped cantilevers, cases (i) max axial and (ii) max eccentric moment', 'เสาเข็มตอม่อกลาง: กรณี (i) แรงอัดสูงสุด (ii) โมเมนต์เยื้องศูนย์สูงสุด')) +
          `<h4 class="cn-h4">${T('Halfcap', 'คานหัวเสา')}</h4><div class="tb-form">${fld(base + 'cap.b', T('Total width (both halfcaps)', 'ความกว้างรวม'), { num: 1 }, 'm')}${fld(base + 'cap.bh', T('Width of one halfcap', 'ความกว้างคานหัวเสาหนึ่งตัว'), { num: 1 }, 'm')}${fld(base + 'cap.d', T('Depth', 'ความลึก'), { num: 1 }, 'm')}${fld(base + 'cap.E', 'E', { num: 1 }, 'MPa')}${fld(base + 'cap.mat', T('Species', 'ชนิดไม้'), { sel: MATS.slice(0, 5) })}${fld(base + 'cap.grade', T('Grade', 'ชั้นคุณภาพ'), { sel: GRS })}${fld(base + 'cap.bear', T('Bearing on pile (default)', 'ระยะแบกบนเสาเข็ม'), { num: 1 }, 'mm')}${fld(base + 'cap.cond', T('Condition', 'สภาพ'), { sel: CONDS })}${fld(base + 'share', T('Live load share on one halfcap (blank = 0.667 pier / 1.0 abutment; 0.5 for two abutment halfcaps)', 'สัดส่วนน้ำหนักจรต่อคานหัวเสาหนึ่งตัว (ว่าง = 0.667 ตอม่อกลาง / 1.0 ตอม่อริม; 0.5 สำหรับคานคู่ที่ตอม่อริม)'), { num: 1 })}</div>
          <h4 class="cn-h4">${T('Piles', 'เสาเข็ม')}</h4><div class="cn-tbl tb-piles"><table><thead><tr>${cols.map(c => `<th>${c[1]}</th>`).join('')}<th></th></tr></thead><tbody>${piles}</tbody></table></div><div class="cn-btns"><button class="btn btn-ghost xs" data-act="tb-rb" data-c="pileadd" data-v="${kk}">+ ${T('pile', 'เสาเข็ม')}</button></div>
          <p class="cn-note">${T('Defect 1: concentric pipe radius r. Defect 2: elliptical hole from solid thicknesses L, R, B (back), F (front) in mm. e = pile radius − half the bearing width. Critical depth = depth of the defect below ground (negative above).', 'ตำหนิ 1: โพรงกลมรัศมี r; ตำหนิ 2: โพรงวงรีจากความหนาเนื้อไม้ L, R, B, F (มม.); e = รัศมีเสาเข็ม − ครึ่งหนึ่งของระยะแบก')}</p>` +
          (abut ? `<h4 class="cn-h4">${T('Wing walls', 'กำแพงปีก')}</h4>${wings}<div class="cn-btns"><button class="btn btn-ghost xs" data-act="tb-rb" data-c="wadd" data-v="${kk}">+ ${T('Wing wall', 'กำแพงปีก')}</button></div>` : ''); }
      if (k === 'res' || k === 'repairs') return resultsSummary(k === 'repairs');
      if (k.startsWith('rs:')) return resultsSpan(+k.slice(3));
      if (k.startsWith('ru:')) return resultsSupport(+k.slice(3));
      return head(T('Select an item in the tree', 'เลือกรายการในผัง'));
    }
    function secSVG(sec) { const P = sec.outer, V = sec.void; const xs = P.map(p => p[0]), ys = P.map(p => p[1]), x0 = Math.min(...xs), x1 = Math.max(...xs), y0 = Math.min(...ys), y1 = Math.max(...ys), w = x1 - x0, h = y1 - y0, k = 34 / Math.max(w, h), pt = p => ((p[0] - x0) * k + 1).toFixed(1) + ',' + ((y1 - p[1]) * k + 1).toFixed(1); return `<svg class="tb-sec" viewBox="0 0 ${w * k + 2} ${h * k + 2}" width="${(w * k + 2).toFixed(0)}" height="${(h * k + 2).toFixed(0)}"><polygon points="${P.map(pt).join(' ')}"/>${V ? `<polygon class="v" points="${V.map(pt).join(' ')}"/>` : ''}</svg>`; }

    // ------------------------------------------------------------------ results
    const rt = (r, W) => (!r || r.skip ? '<td class="num muted">—</td>' : `<td class="num ${r.t < W ? 'bad' : ''}">${fmt(r.t, 1)}</td>`);
    function resultsSummary(repairsOnly) {
      const R = A.R; if (!R || A.stale) return `<div class="cn-ph"><b>${T('Results', 'ผลลัพธ์')}</b></div><p class="cn-note">${T('Press Analyse & rate.', 'กด วิเคราะห์และประเมิน')}</p>`;
      const sm = R.summary, v = vids();
      let h = `<div class="cn-ph"><b>${T('Load rating summary — Bridge ', 'สรุปการประเมินกำลังรับน้ำหนัก — สะพาน ')}${esc(A.B.no || '')}</b><span class="muted small">k1 = ${f(R.k1, 2)} · ${R.ms} ms · ${T('ratings below the vehicle weight are highlighted', 'ค่าที่ต่ำกว่าน้ำหนักยานพาหนะถูกเน้นสี')}</span></div>`;
      if (!repairsOnly) {
        h += `<div class="cn-tbl"><table><thead><tr><th>${T('Vehicle', 'ยานพาหนะ')}</th><th class="num">${T('Rating (t)', 'กำลังรับ (ตัน)')}</th><th class="num">%</th><th>${T('Governing component', 'ชิ้นส่วนควบคุม')}</th><th>${T('Critical', 'กรณีวิกฤต')}</th></tr></thead><tbody>${v.map(id => { const r = sm.rows[id]; return r ? `<tr class="${r.pct < 100 ? 'bad' : ''}"><td><b>${VN(id)}</b></td><td class="num">${fmt(r.t, 1)}</td><td class="num">${f(r.pct, 0)}%</td><td>${esc(r.comp)}</td><td>${esc(r.crit || '')}</td></tr>` : `<tr><td>${VN(id)}</td><td colspan="4" class="muted">${T('not analysed', 'ไม่ได้วิเคราะห์')}</td></tr>`; }).join('')}</tbody></table></div>`;
        h += `<p class="tb-limit">${sm.limit ? `<b class="bad">${T('Load limit (posting): ', 'ป้ายจำกัดน้ำหนัก: ')}${f(sm.limit.t, 1)} t</b> — ${esc(sm.limit.rule)}` : `<b class="ok">${T('No load limit required by the M-Truck / Tandem / Triaxle rules.', 'ไม่ต้องจำกัดน้ำหนักตามเกณฑ์ M-Truck / Tandem / Triaxle')}</b>`}</p>`;
        if (R.warn.length) h += `<p class="cn-note bad">${R.warn.map(esc).join('<br>')}</p>`;
      }
      // elements below 100% grouped -> repair suggestions
      const fam = c => (/stringer/i.test(c) ? 'stringer' : /halfcap bearing/i.test(c) ? 'bearing' : /halfcap/i.test(c) ? 'halfcap' : /planks/i.test(c) ? 'planks' : /Abutment.*pile/i.test(c) ? 'abutPile' : /pile/i.test(c) ? 'pierPile' : 'other');
      const by = {}; sm.low.forEach(l => { const k = l.comp; (by[k] = by[k] || []).push(l); });
      const wingFail = R.supports.filter(Boolean).flatMap(su => su.wing.filter(w => !w.ok).map(w => su.name + ' ' + w.name));
      h += `<h4 class="cn-h4">${T('Elements below 100 % for any vehicle', 'ชิ้นส่วนที่ต่ำกว่า 100 % สำหรับยานพาหนะใด ๆ')} (${Object.keys(by).length})</h4>`;
      if (!Object.keys(by).length && !wingFail.length) h += `<p class="cn-note ok">${T('All rated elements carry every selected vehicle at 100 % or more.', 'ทุกชิ้นส่วนรับยานพาหนะที่เลือกได้ไม่น้อยกว่า 100 %')}</p>`;
      else h += `<div class="cn-tbl"><table><thead><tr><th>${T('Element', 'ชิ้นส่วน')}</th><th>${T('Vehicles below 100 %', 'ยานพาหนะที่ต่ำกว่า 100 %')}</th><th>${T('Suggested standard repair details', 'รายละเอียดการซ่อมมาตรฐานที่แนะนำ')}</th></tr></thead><tbody>${Object.entries(by).map(([c, ls]) => { const fm = fam(c), ids = (G.TDET && G.TDET.SUGGEST[fm]) || []; return `<tr class="bad"><td><b>${esc(c)}</b></td><td class="tb-wrap">${ls.map(l => esc(VN(l.vid)) + ' ' + f(l.pct, 0) + '% (' + esc(l.crit || '') + ')').join(', ')}</td><td class="tb-reps">${ids.map(id => { const d = G.TDET.DEF.find(q => q.id === id); return d ? `<button class="btn btn-ghost xs" data-act="tb-rep" data-v="${id}" data-c="${esc(c)}" title="${esc(d.name)}">${esc(d.ref)} ${esc(d.name.replace(/ – .*/, ''))}</button>` : ''; }).join(' ')}</td></tr>`; }).join('')}${wingFail.map(w => `<tr class="bad"><td><b>${esc(w)}</b></td><td>${T('Wing wall piles FAIL', 'เสาเข็มกำแพงปีกไม่ผ่าน')}</td><td>${G.TDET.SUGGEST.wing.map(id => `<button class="btn btn-ghost xs" data-act="tb-rep" data-v="${id}" data-c="${esc(w)}">${esc(G.TDET.DEF.find(q => q.id === id).ref)}</button>`).join(' ')}</td></tr>`).join('')}</tbody></table></div><div class="cn-btns"><button class="btn btn-hot sm" data-act="tb-rb" data-c="drawall">${T('Open all suggested details in the repair drawing', 'เปิดรายละเอียดที่แนะนำทั้งหมดในแบบซ่อม')}</button></div>`;
      return h;
    }
    function resultsSpan(i) {
      const R = A.R, sp = R && R.spans[i]; if (!sp) return ''; const v = vids();
      let h = `<div class="cn-ph"><b>${T('Span ', 'ช่วง ')}${i + 1} — ${T('stringer ratings (t)', 'กำลังรับของคาน (ตัน)')}</b><span class="muted small">L ${f(sp.gm.L, 2)} m · Le ${f(sp.gm.Le, 3)} m · ${T('governing = min(bending, shear end 1, shear end 2)', 'ควบคุม = min(ดัด, เฉือนปลาย 1, เฉือนปลาย 2)')}</span></div>`;
      h += `<div class="cn-tbl"><table><thead><tr><th>${T('Stringer', 'คาน')}</th><th class="num">I<sub>mid</sub> ×10⁹</th><th class="num">y<sub>max</sub></th><th class="num">M<sub>all</sub></th><th class="num">V<sub>all,1</sub></th><th class="num">V<sub>all,2</sub></th><th class="num">M<sub>DL</sub></th><th class="num">V<sub>DL1</sub></th><th class="num">V<sub>DL2</sub></th>${v.map(id => `<th class="num">${VN(id)}</th>`).join('')}</tr></thead><tbody>${sp.str.map(s => `<tr><td><b>S${s.s}</b> <span class="muted small">${esc(s.info.grade)}</span></td><td class="num">${f(s.info.I / 1e9, 3)}</td><td class="num">${f(s.info.ymax, 1)}</td><td class="num">${f(s.Mcap, 1)}</td><td class="num">${f(s.V1cap, 1)}</td><td class="num">${f(s.V2cap, 1)}</td><td class="num">${f(s.DL.M, 2)}</td><td class="num">${f(s.DL.V1, 2)}</td><td class="num">${f(s.DL.V2, 2)}</td>${v.map(id => rt(s.veh[id], (TB.vehicle(id) || {}).W)).join('')}</tr>`).join('')}</tbody></table></div>`;
      h += `<h4 class="cn-h4">${T('Bending / shear end 1 / shear end 2 ratings (t)', 'กำลังรับจากการดัด / เฉือนปลาย 1 / เฉือนปลาย 2 (ตัน)')}</h4><div class="cn-tbl"><table><thead><tr><th>${T('Vehicle', 'ยานพาหนะ')}</th>${sp.str.map(s => `<th class="num">S${s.s}</th>`).join('')}</tr></thead><tbody>${v.map(id => `<tr><td>${VN(id)}</td>${sp.str.map(s => { const r = s.veh[id], W = (TB.vehicle(id) || {}).W; return `<td class="num ${r && !r.skip && r.t < W ? 'bad' : ''}">${r && !r.skip ? [r.rb, r.r1, r.r2].map(x => (x === 0 ? '0' : fmt(x, 1))).join(' / ') + (r.dlx ? ' ⚠' : '') : '—'}</td>`; }).join('')}</tr>`).join('')}</tbody></table></div>` +
        (sp.str.some(s => Object.values(s.veh).some(r => r && r.dlx)) ? `<p class="cn-note bad">⚠ ${T('Dead load alone exceeds the capacity: rating 0.', 'น้ำหนักคงที่เพียงอย่างเดียวเกินกำลัง: กำลังรับ 0')}</p>` : '') +
        `<p class="cn-note">${T('Section properties: A end 1 / A end 2 (net, mm²) — ', 'คุณสมบัติหน้าตัด: A ปลาย 1 / ปลาย 2 (สุทธิ มม.²) — ')}${sp.str.map(s => 'S' + s.s + ' ' + f(s.info.A1, 0) + ' / ' + f(s.info.A2, 0) + (s.info.sawn ? T(' sawn', ' ไม้เลื่อย') : '')).join(' · ')}</p>`;
      h += `<h4 class="cn-h4">${T('Live load effects per vehicle (kNm, kN, without DLA)', 'ผลน้ำหนักจรต่อยานพาหนะ (ไม่รวม DLA)')}</h4><div class="cn-tbl"><table><thead><tr><th>${T('Vehicle', 'ยานพาหนะ')}</th>${sp.str.map(s => `<th class="num">S${s.s} M / V1 / V2</th>`).join('')}</tr></thead><tbody>${v.map(id => `<tr><td>${VN(id)}</td>${sp.str.map(s => { const r = s.veh[id]; return `<td class="num">${r && !r.skip ? f(r.LL.M, 1) + ' / ' + f(r.LL.V1, 1) + ' / ' + f(r.LL.V2, 1) : '—'}</td>`; }).join('')}</tr>`).join('')}</tbody></table></div>`;
      if (sp.planks) { const p = sp.planks; h += `<h4 class="cn-h4">${T('Deck planks', 'แผ่นพื้นไม้')}</h4><p class="cn-note">d<sub>eff</sub> ${f(p.deff, 0)} mm, b<sub>eff</sub> ${f(p.beff, 0)} mm · F<sub>b</sub> ${f(p.Fb, 2)} MPa, F<sub>s</sub> ${f(p.Fs, 2)} MPa · M<sub>cap</sub> ${f(p.Mcap, 2)} kNm, V<sub>cap</sub> ${f(p.Vcap, 2)} kN · T44 M<sub>LL</sub> ${f(p.LM, 2)} kNm, V<sub>LL</sub> ${f(p.LV, 2)} kN (incl. DLA)</p><div class="cn-tbl"><table><thead><tr>${Object.keys(p.veh).map(id => `<th class="num">${VN(id)}</th>`).join('')}</tr></thead><tbody><tr>${Object.values(p.veh).map(r => `<td class="num ${r.t < r.W ? 'bad' : ''}">${f(r.t, 1)} t · ${f(r.pct, 0)}%</td>`).join('')}</tr></tbody></table></div>`; }
      return h;
    }
    function resultsSupport(k) {
      const R = A.R, su = R && R.supports[k]; if (!su) return ''; const v = vids(), pier = su.kind === 'pier';
      let h = `<div class="cn-ph"><b>${esc(su.name)} — ${T('pile ratings (t)', 'กำลังรับของเสาเข็ม (ตัน)')}</b><span class="muted small">${pier ? T('Propped cantilever: (i) max axial, (ii) max eccentric moment; top and critical sections; f_b/F_b + f_c/F_c ≤ 1', 'คานยื่นค้ำปลาย: (i) แรงอัดสูงสุด (ii) โมเมนต์เยื้องศูนย์; หน้าตัดบนและวิกฤต') : T('Case 1 max soil + min live load; case 2 min soil + max live load (top, critical, fixed sections)', 'กรณี 1 แรงดันดินสูงสุด; กรณี 2 แรงดันดินต่ำสุด + น้ำหนักจรสูงสุด')}</span></div>`;
      h += `<div class="cn-tbl"><table><thead><tr><th>${T('Pile', 'เสาเข็ม')}</th><th class="num">A<sub>crit</sub> (m²)</th><th class="num">Z<sub>min</sub> (m³)</th><th class="num">S</th><th class="num">k12</th><th class="num">P<sub>cap</sub></th><th class="num">M<sub>cap</sub></th><th class="num">D1 / D2</th>${v.map(id => `<th class="num">${VN(id)}</th>`).join('')}</tr></thead><tbody>${su.piles.map(p => `<tr><td><b>${esc(p.p)}</b></td><td class="num">${f(p.cp.crit.A, 4)}</td><td class="num">${f(p.cp.crit.Zmin, 5)}</td><td class="num">${f(p.cp.S, 2)}</td><td class="num">${f(p.cp.k12, 2)}</td><td class="num">${f(p.cp.crit.P, 0)}</td><td class="num">${f(p.cp.crit.M, 1)}</td><td class="num">${f(p.D1, 1)} / ${f(p.D2, 1)}</td>${v.map(id => rt(p.veh[id], (TB.vehicle(id) || {}).W)).join('')}</tr>`).join('')}</tbody></table></div>`;
      h += `<h4 class="cn-h4">${T('Pile loads (kN, without DLA)', 'แรงในเสาเข็ม (kN ไม่รวม DLA)')}</h4><div class="cn-tbl"><table><thead><tr><th>${T('Pile', 'เสาเข็ม')}</th>${v.map(id => `<th class="num">${VN(id)} ${pier ? 'ax R1/R2 · mom' : 'ax'}</th>`).join('')}</tr></thead><tbody>${su.piles.map(p => `<tr><td>${esc(p.p)}</td>${v.map(id => { const l = p.load && p.load[id]; return `<td class="num">${l ? (pier ? f(l.ax1, 1) + '/' + f(l.ax2, 1) + ' · ' + f(Math.max(l.m1, l.m2), 1) : f(l.ax1 + l.ax2, 1)) : '—'}</td>`; }).join('')}</tr>`).join('')}</tbody></table></div>`;
      h += `<h4 class="cn-h4">${T('Governing case per pile', 'กรณีควบคุมของแต่ละเสาเข็ม')}</h4><div class="cn-tbl"><table><thead><tr><th>${T('Pile', 'เสาเข็ม')}</th>${v.map(id => `<th>${VN(id)}</th>`).join('')}</tr></thead><tbody>${su.piles.map(p => `<tr><td>${esc(p.p)}</td>${v.map(id => { const r = p.veh[id]; return `<td class="small">${r && !r.skip ? esc(r.crit || '') : '—'}</td>`; }).join('')}</tr>`).join('')}</tbody></table></div>`;
      if (pier) h += `<p class="cn-note">${T('Pile top sections (defect free): ', 'หน้าตัดบนของเสาเข็ม (ไม่มีตำหนิ): ')}${su.piles.map(p => esc(p.p) + ' P ' + f(p.cp.top.P, 0) + ' kN, M ' + f(p.cp.top.M, 1) + ' kNm').join(' · ')} · L / L<sub>e</sub> / P<sub>cr</sub>: ${su.piles.map(p => esc(p.p) + ' ' + f(p.cp.L, 2) + ' / ' + f(p.cp.Le, 2) + ' m / ' + f(p.cp.Pcr, 0) + ' kN').join(' · ')}</p>`;
      else { const r0 = p => p.veh[v.find(id => p.veh[id] && !p.veh[id].skip)] || {};
        h += `<h4 class="cn-h4">${T('Abutment pile checks (kN, MPa)', 'การตรวจสอบเสาเข็มตอม่อริม (kN, MPa)')}</h4><div class="cn-tbl"><table><thead><tr><th>${T('Pile', 'เสาเข็ม')}</th><th class="num">${T('Case 1 live (max soil)', 'กรณี 1 น้ำหนักจร (ดินสูงสุด)')}</th><th class="num">${T('Case 2 top', 'กรณี 2 บน')}</th><th class="num">${T('Case 2 critical', 'กรณี 2 วิกฤต')}</th><th class="num">${T('Case 2 fixed', 'กรณี 2 จุดยึด')}</th><th class="num">${T('Shear f_v/F_s', 'แรงเฉือน f_v/F_s')}</th><th class="num">${T('Tension σ_t / F_b,t', 'แรงดึง σ_t / F_b,t')}</th></tr></thead><tbody>${su.piles.map(p => { const r = r0(p); return `<tr><td>${esc(p.p)}</td><td class="num">${fmt(r.case1, 1)}</td><td class="num">${fmt(r.case2Top, 1)}</td><td class="num">${fmt(r.case2Crit, 1)}</td><td class="num">${fmt(r.case2Fix, 1)}</td><td class="num ${r.shearOK === false ? 'bad' : ''}">${fmt(r.shear1, 2)} ${r.shearOK === false ? 'FAIL' : 'PASS'}</td><td class="num ${r.tensionOK === false ? 'bad' : ''}">${fmt(r.sigT, 2)} / ${fmt(p.cp.Fbt, 2)} ${r.tensionOK === false ? 'FAIL' : 'PASS'}</td></tr>`; }).join('')}</tbody></table></div>`; }
      h += `<h4 class="cn-h4">${T('Halfcap bearing on piles (t)', 'แรงแบกคานหัวเสาบนเสาเข็ม (ตัน)')}</h4><div class="cn-tbl"><table><thead><tr><th>${T('Pile', 'เสาเข็ม')}</th><th class="num">${T('Bearing area', 'พื้นที่แบก')} (mm²)</th><th class="num">${T('Capacity', 'กำลัง')} (kN)</th>${v.map(id => `<th class="num">${VN(id)}</th>`).join('')}</tr></thead><tbody>${su.piles.map(p => { const b0 = Object.values(p.bear)[0] || {}; return `<tr><td>${esc(p.p)}</td><td class="num">${f(b0.A || 0, 0)}</td><td class="num">${f(b0.Cap || 0, 1)}</td>${v.map(id => rt(p.bear[id], (TB.vehicle(id) || {}).W)).join('')}</tr>`; }).join('')}</tbody></table></div>${pier ? `<p class="cn-note">${T('Each facing halfcap is checked with its own dead load and 2/3 of the pile live load; the lower side is shown.', 'ตรวจคานหัวเสาแต่ละด้านด้วยน้ำหนักคงที่ของด้านนั้นและ 2/3 ของน้ำหนักจร แสดงด้านที่ต่ำกว่า')}</p>` : ''}`;
      if (su.halfcap) { const hc = su.halfcap; h += `<h4 class="cn-h4">${T('Halfcap (continuous beam on piles)', 'คานหัวเสา (คานต่อเนื่องบนเสาเข็ม)')}</h4><p class="cn-note">F<sub>b</sub> ${f(hc.Fb, 2)} MPa · F<sub>s</sub> ${f(hc.Fs, 2)} MPa · Z ${f(hc.Z / 1e6, 3)}×10⁶ mm³ · A<sub>s</sub> ${f(hc.As, 0)} mm² · M<sub>DL</sub> ${f(hc.MD, 2)} kNm · V<sub>DL</sub> ${f(hc.VD, 2)} kN · ${T('live load share', 'สัดส่วนน้ำหนักจร')} ${f(hc.share, 3)}</p><div class="cn-tbl"><table><thead><tr><th>${T('Vehicle', 'ยานพาหนะ')}</th><th class="num">${T('Bending (t)', 'ดัด (ตัน)')}</th><th>${T('at', 'ที่')}</th><th class="num">${T('Shear (t)', 'เฉือน (ตัน)')}</th><th>${T('at', 'ที่')}</th><th class="num">${T('Rating (t)', 'กำลังรับ (ตัน)')}</th></tr></thead><tbody>${Object.entries(hc.veh).map(([id, r]) => `<tr class="${r.t < (TB.vehicle(id) || {}).W ? 'bad' : ''}"><td>${VN(id)}</td><td class="num">${fmt(r.tM, 1)}</td><td class="small">${esc(r.locM || '')}</td><td class="num">${fmt(r.tV, 1)}</td><td class="small">${esc(r.locV || '')}</td><td class="num"><b>${fmt(r.t, 1)}</b></td></tr>`).join('')}</tbody></table></div><p class="cn-note">M<sub>cap</sub> ${f(hc.Mcap, 2)} kNm · V<sub>cap</sub> ${f(hc.Vcap, 2)} kN · ${T('dead and live effects taken at the same location (moments at the nodes, shear at the pile faces)', 'น้ำหนักคงที่และน้ำหนักจรคิดที่ตำแหน่งเดียวกัน (โมเมนต์ที่จุดต่อ แรงเฉือนที่ผิวเสาเข็ม)')}</p>`; }
      su.wing.forEach(w => { h += `<h4 class="cn-h4">${esc(w.name)} — ${w.ok ? `<span class="ok">PASS</span>` : `<span class="bad">FAIL</span>`}</h4><div class="cn-tbl"><table><thead><tr><th>${T('Pile', 'เสาเข็ม')}</th><th class="num">H</th><th class="num">${T('Width', 'ความกว้าง')}</th><th class="num">M fixed</th><th class="num">V fixed</th><th class="num">M crit</th><th class="num">V crit</th><th class="num">M<sub>r</sub> / V<sub>r</sub> fixed</th><th class="num">M<sub>r</sub> / V<sub>r</sub> crit</th><th class="num">${T('Capacity / demand', 'กำลัง / แรง')}</th></tr></thead><tbody>${w.piles.map(p => `<tr class="${p.ok ? '' : 'bad'}"><td>${esc(p.p)}</td><td class="num">${f(p.H, 2)}</td><td class="num">${f(p.wt, 3)}</td><td class="num">${f(p.Mf, 2)}</td><td class="num">${f(p.Vf, 2)}</td><td class="num">${f(p.Mc, 2)}</td><td class="num">${f(p.Vc, 2)}</td><td class="num">${f(p.MrF, 1)} / ${f(p.VrF, 1)}</td><td class="num">${f(p.MrC, 1)} / ${f(p.VrC, 1)}</td><td class="num">${[p.rMF, p.rVF, p.rMC, p.rVC].map(x => f(x, 2)).join(' / ')}</td></tr>`).join('')}</tbody></table></div><p class="cn-note">β ${f(w.piles[0] ? w.piles[0].beta : 0, 2)}° · Ka1 ${f(w.piles[0] ? w.piles[0].Ka1 : 0, 3)} · Ka2 ${f(w.piles[0] ? w.piles[0].Ka2 : 0, 3)} · Kp ${f(w.piles[0] ? w.piles[0].Kp : 0, 3)} · ${T('approximate earth-pressure model — check marginal piles by hand', 'แบบจำลองแรงดันดินโดยประมาณ — ตรวจสอบเสาเข็มที่ใกล้เกณฑ์ด้วยมือ')}</p>`; });
      return h;
    }

    // ------------------------------------------------------------------ schematic (elevation + plan of the selected span)
    function schematic() {
      const B = A.B, R = A.R && !A.stale ? A.R : null, W = 1000, H = 300;
      const Ltot = B.spans.reduce((a, s) => a + (+s.L || 0), 0) || 1, k = (W - 40) / Ltot; let x = 20, s = '';
      const selSpan = /^(span|str|patch|plank|rs):(\d+)/.exec(A.sel), si = selSpan ? +selSpan[2] : 0, selSup = /^(sup|ru):(\d+)/.exec(A.sel);
      // elevation
      s += `<text x="20" y="16" class="tb-st">${T('ELEVATION', 'รูปด้านข้าง')}</text>`;
      const xs = [x]; B.spans.forEach(S => { x += (+S.L || 0) * k; xs.push(x); });
      B.spans.forEach((S, i) => { const sp = R && R.spans[i], p = sp ? Math.min(...sp.str.map(q => (q.veh.T44 && q.veh.T44.pct) || Infinity)) : NaN; s += `<rect x="${xs[i]}" y="40" width="${xs[i + 1] - xs[i]}" height="16" class="tb-deck ${i === si && selSpan ? 'on' : ''} ${pctCls(p)}" data-act="tb-sel" data-k="span:${i}"/><text x="${(xs[i] + xs[i + 1]) / 2}" y="76" class="tb-sl">${T('Span ', 'ช่วง ')}${i + 1} · ${f(+S.L, 2)} m${isFinite(p) ? ' · T44 ' + f(p, 0) + '%' : ''}</text>`; });
      xs.forEach((xx, kk) => { const Su = (B.supports || [])[kk] || {}, np = (Su.piles || []).length, on = selSup && +selSup[2] === kk, su = R && R.supports[kk], p = su ? Math.min(...su.piles.map(q => (q.veh.T44 ? q.veh.T44.t / 44.04 * 100 : Infinity))) : NaN; s += `<g class="tb-sup ${on ? 'on' : ''} ${pctCls(p)}" data-act="tb-sel" data-k="sup:${kk}"><rect x="${xx - 9}" y="56" width="18" height="8"/>${Array.from({ length: Math.min(np, 4) }, (_, j) => `<line x1="${xx - 6 + j * 4}" y1="64" x2="${xx - 6 + j * 4}" y2="${kk === 0 || kk === B.spans.length ? 100 : 120}"/>`).join('')}<text x="${xx}" y="${kk === 0 || kk === B.spans.length ? 112 : 132}" class="tb-sl">${kk === 0 ? 'A1' : kk === B.spans.length ? 'A2' : 'P' + kk}</text></g>`; });
      s += `<line x1="10" y1="${105}" x2="${W - 10}" y2="${105}" class="tb-gl"/>`;
      // plan of the selected span
      const S = B.spans[si]; if (S) { let gm = null; try { gm = TB.spanGeom(B, si); } catch (e) { }
        if (gm) { const px = 120, py = 155, pw = W - 240, ph = 125, kx = pw / gm.L, ky = ph / Math.max(gm.width, 0.1), X = v => px + v * kx, Y = v => py + v * ky, sp = R && R.spans[si];
          s += `<text x="20" y="${py - 8}" class="tb-st">${T('PLAN — SPAN ', 'แปลน — ช่วง ')}${si + 1}</text><rect x="${X(0)}" y="${Y(0)}" width="${gm.L * kx}" height="${gm.width * ky}" class="tb-pdeck"/><rect x="${X(0)}" y="${Y(0)}" width="${gm.L * kx}" height="${gm.cw0 * ky}" class="tb-kerb"/><rect x="${X(0)}" y="${Y(gm.cw1)}" width="${gm.L * kx}" height="${(gm.width - gm.cw1) * ky}" class="tb-kerb"/>`;
          s += `<line x1="${X(gm.xs0)}" y1="${Y(0) - 6}" x2="${X(gm.xs0)}" y2="${Y(gm.width) + 6}" class="tb-cl"/><line x1="${X(gm.xs1)}" y1="${Y(0) - 6}" x2="${X(gm.xs1)}" y2="${Y(gm.width) + 6}" class="tb-cl"/>`;
          gm.ys.forEach((y, j) => { const r = sp && sp.str[j], p = r && r.veh.T44 ? r.veh.T44.pct : NaN; s += `<line x1="${X(0)}" y1="${Y(y)}" x2="${X(gm.L)}" y2="${Y(y)}" class="tb-strl ${pctCls(p)}"/><text x="${X(0) - 6}" y="${Y(y) + 3}" class="tb-sl" text-anchor="end">S${j + 1}${isFinite(p) ? ' ' + f(p, 0) + '%' : ''}</text>`; });
          const Su0 = B.supports[si] || {}, Su1 = B.supports[si + 1] || {}; (Su0.piles || []).forEach(p => { s += `<circle cx="${X(0)}" cy="${Y(+p.x)}" r="${Math.max(2.5, (+p.d || 350) / 1000 * ky / 2)}" class="tb-pile"/>`; }); (Su1.piles || []).forEach(p => { s += `<circle cx="${X(gm.L)}" cy="${Y(+p.x)}" r="${Math.max(2.5, (+p.d || 350) / 1000 * ky / 2)}" class="tb-pile"/>`; });
          s += `<text x="${X(gm.L) + 8}" y="${Y(gm.width / 2)}" class="tb-sl">${f(gm.width, 2)} m</text>`; } }
      return `<svg class="tb-sch" viewBox="0 0 ${W} ${H}" preserveAspectRatio="xMidYMid meet" role="img" aria-label="${T('Bridge elevation and span plan', 'รูปด้านและแปลนสะพาน')}">${s}</svg>`;
    }

    // ------------------------------------------------------------------ page
    function view() {
      return `<main class="an an-app tb-app">${ribHTML()}<aside class="an-side tb-side" id="tbTree">${treeHTML()}</aside>
        <section class="tb-work"><div class="tb-schw" id="tbSch">${schematic()}</div><div class="tb-panel" id="tbPanel">${panelHTML()}</div></section>
        <div id="reportWrap" class="an-report"></div></main>`;
    }
    function refresh(all) { const t = $('#tbTree'); if (t) t.innerHTML = treeHTML(); const s = $('#tbSch'); if (s) s.innerHTML = schematic(); if (all !== false) { const p = $('#tbPanel'); if (p) p.innerHTML = panelHTML(); } ribRefresh(); }
    function run() {
      if (A.busy) return; A.busy = true; ribRefresh(); toast(T('Analysing the grillages and rating the components…', 'กำลังวิเคราะห์กริลเลจและประเมินชิ้นส่วน…'), '');
      setTimeout(() => { try { A.R = TB.analyse(A.B); A.stale = false; A.sel = 'res'; const lo = A.R.summary.low.length; toast(T('Load rating complete — ', 'ประเมินเสร็จ — ') + (lo ? lo + T(' elements below 100 %', ' ชิ้นส่วนต่ำกว่า 100 %') : T('all elements ≥ 100 %', 'ทุกชิ้นส่วน ≥ 100 %')) + ' (' + A.R.ms + ' ms)', lo ? 'bad' : 'ok'); } catch (e) { toast(T('Analysis failed: ', 'วิเคราะห์ไม่สำเร็จ: ') + (e && e.message || e), 'bad'); } A.busy = false; render(); }, 40);
    }
    function queueRepairs(list) { try { const q = JSON.parse(localStorage.getItem('sc.tdraw.queue') || '[]'); list.forEach(x => q.push(x)); localStorage.setItem('sc.tdraw.queue', JSON.stringify(q)); } catch (e) { } }
    function repairParams(det, comp) { // fill parameters from the bridge data where we can
      const B = A.B, m = /(Pier|Abutment) (\d+) pile (\w+)/.exec(comp || ''), out = {};
      if (m) { const kk = m[1] === 'Pier' ? +m[2] : (m[2] === '1' ? 0 : B.spans.length), pl = ((B.supports[kk] || {}).piles || []).find((p, i) => String(p.id || i + 1) === m[3]); if (pl) out.D = +pl.d; }
      if (det === 'phs') { const kk = /Pier (\d+)/.exec(comp || ''); const Su = kk ? B.supports[+kk[1]] : null; if (Su && Su.piles.length > 1) { out.piles = Su.piles.slice(1).map((p, i) => Math.round((+p.x - +Su.piles[i].x) * 1000)).join(', '); out.D = +Su.piles[0].d; out.hc = Math.round((+Su.cap.d || 0.3) * 1000); out.ns = (B.spans[+kk[1] - 1] || B.spans[0]).stringers.length; } }
      return out;
    }

    // ------------------------------------------------------------------ report
    function renderReport() {
      if (!isPro()) { toast(T('The timber rating report is a Pro feature.', 'รายงานการประเมินสะพานไม้สำหรับสมาชิก Pro'), 'bad'); return; }
      if (!A.R || A.stale) { toast(T('Analyse the bridge first.', 'วิเคราะห์สะพานก่อน'), 'bad'); return; }
      const B = A.B, R = A.R, Mt = S.meta || {}, v = vids();
      const sec = (n, title, html) => `<section class="rp-sec"><h3><span class="rp-n">${n}</span>${title}</h3>${html}</section>`;
      const clean = h => h.replace(/<input[^>]*value="([^"]*)"[^>]*>/g, '$1').replace(/<button[^>]*>.*?<\/button>/g, '').replace(/class="cn-tbl"/g, 'class="rp-tw"').replace(/<table>/g, '<table class="rp-t an-rp">');
      let html = sec(1, T('Bridge and method', 'สะพานและวิธีการ'), `<p class="rp-txt">${esc(B.no)} — ${esc(B.name || '')}. ${T('Road type', 'ประเภทถนน')}: ${B.road === 'main' ? T('main road, k1 = 1.40', 'ถนนสายหลัก k1 = 1.40') : T('local road, k1 = 1.65', 'ถนนท้องถิ่น k1 = 1.65')}. ${B.spans.length} ${T('spans', 'ช่วง')}.</p><p class="rp-txt">${T('Load rating by working stress to AS 1720.1-1988 and AS 3990 following MRWA practice (TIMBAR procedure, Load Rating and Refurbishment Design Manual for Existing Timber Bridges). Rating factor RF = (capacity − dead load effect) / (vehicle effect × (1 + DLA)); rating (t) = RF × vehicle weight. Each span is a grillage of stringers on Le = (L + Lo)/2 with transverse deck members; vehicles are stepped along and across the carriageway; dead load includes self weight and patch loads. Rot and friable timber are excluded from the section properties; condition factors reduce permissible stresses.', 'ประเมินด้วยหน่วยแรงใช้งานตาม AS 1720.1-1988 และ AS 3990 ตามแนวทาง MRWA; RF = (กำลัง − ผลน้ำหนักคงที่) / (ผลยานพาหนะ × (1 + DLA)); กำลังรับ (ตัน) = RF × น้ำหนักยานพาหนะ')}</p>` +
        `<p class="rp-txt"><b>${T('Assumptions', 'สมมติฐาน')}</b></p><ul class="rp-txt">${[
          T('Methods: TIMBAR Procedure Manual (Main Roads WA, v1.1.5) and the Load Rating & Refurbishment Design Manual for Existing Timber Bridges (MRWA 6706-02-2227).', 'วิธีการ: คู่มือขั้นตอน TIMBAR (MRWA v1.1.5) และคู่มือการประเมินกำลังรับน้ำหนักและออกแบบซ่อมแซมสะพานไม้ (MRWA 6706-02-2227)'),
          T('Tandem, triaxle and quad groups run with their prime mover (6 t steer + 16.5 t drive) whenever it is on the bridge; the rating weight is the axle group only.', 'กลุ่มเพลาแทนเดม ไตรแอกเซิล ควอด วิ่งพร้อมหัวลากเมื่ออยู่บนสะพาน น้ำหนักประเมินคิดเฉพาะกลุ่มเพลา'),
          T('Stringer bending uses the maximum live-load moment along the stringer; shear at the faces of support (0.3 m from an abutment centreline).', 'การดัดของคานใช้โมเมนต์น้ำหนักจรสูงสุดตลอดความยาว แรงเฉือนที่ผิวจุดรองรับ (0.3 ม. จากศูนย์กลางตอม่อริม)'),
          T('Two vehicles side by side: T44 0.9 + 0.9, M1600 1.0 + 0.8, on the deck and the substructure. M1600 includes the 6 kN/m lane load and is recorded only (not a deficiency).', 'ยานพาหนะสองคันคู่กัน: T44 0.9 + 0.9, M1600 1.0 + 0.8 ทั้งพื้นและโครงสร้างส่วนล่าง M1600 รวมน้ำหนักแผ่ 6 kN/m และบันทึกไว้เท่านั้น'),
          T('Halfcap: dead and live effects at the same location; live load share 2/3 at a pier (corbel action), 1.0 at an abutment unless set.', 'คานหัวเสา: น้ำหนักคงที่และน้ำหนักจรที่ตำแหน่งเดียวกัน สัดส่วนน้ำหนักจร 2/3 ที่ตอม่อกลาง 1.0 ที่ตอม่อริม'),
          T('Deck planks: every pair of wheel positions with patch centres at least 0.6 m from the kerb (a little conservative compared with a single hand-placed position).', 'แผ่นพื้น: ทุกตำแหน่งล้อที่ศูนย์กลางห่างขอบทางอย่างน้อย 0.6 ม. (ปลอดภัยกว่าการวางตำแหน่งเดียวเล็กน้อย)'),
          T('Compression perpendicular to grain for halfcap bearing: Jarrah 6.6, Wandoo 7.8, Karri 9.0, Marri 7.8 MPa (LRRD Table B2.4).', 'แรงอัดตั้งฉากเสี้ยนสำหรับการแบก: Jarrah 6.6, Wandoo 7.8, Karri 9.0, Marri 7.8 MPa (LRRD ตาราง B2.4)'),
          T('Wing wall piles: Rankine pressures with sloping backfill and the AS 5100.2 Fig 13.2 surcharge distribution — approximate; check marginal piles by hand.', 'เสาเข็มกำแพงปีก: แรงดันดิน Rankine และการกระจายน้ำหนักจรตาม AS 5100.2 รูป 13.2 — โดยประมาณ ตรวจเสาเข็มที่ใกล้เกณฑ์ด้วยมือ')].map(x => `<li>${x}</li>`).join('')}</ul>`);
      html += sec(2, T('Summary', 'สรุปผล'), clean(resultsSummary(false)));
      let n = 3; R.spans.forEach((sp, i) => { if (sp) html += sec(n++, T('Span ', 'ช่วง ') + (i + 1), clean(resultsSpan(i))); });
      R.supports.forEach((su, k) => { if (su) html += sec(n++, su.name, clean(resultsSupport(k))); });
      $('#reportWrap').innerHTML = `<div class="rp-bar"><h2>${T('Timber bridge load rating report', 'รายงานประเมินกำลังรับน้ำหนักสะพานไม้')}</h2>
        <div class="rp-meta">${[['project', T('Project', 'โครงการ')], ['job', T('Job no.', 'เลขที่งาน')], ['ref', T('Ref.', 'อ้างอิง')], ['by', T('Assessed by', 'ผู้ประเมิน')], ['checked', T('Checked by', 'ผู้ตรวจสอบ')]].map(([k2, l]) => `<label>${l}<input id="meta-${k2}" data-meta="${k2}" value="${esc(Mt[k2] || '')}"></label>`).join('')}</div>
        <div class="rp-btns"><button class="btn btn-hot sm" data-act="pdf" id="pdfBtn">${T('Export PDF', 'ส่งออก PDF')}</button><button class="btn btn-ghost sm" data-act="closeReport">${T('Close', 'ปิด')}</button></div></div>
        <article class="report" id="report" lang="${S.ui}"><header class="rp-head"><div class="rp-brand">${logoMark(34)}<div><b>StructCap</b><small>${T('Timber bridge load rating', 'การประเมินกำลังรับน้ำหนักสะพานไม้')}</small></div></div>
          <table class="rp-hd"><tr><th>${T('Project', 'โครงการ')}</th><td id="rv-project">${esc(Mt.project || '')}</td><th>${T('Job no.', 'เลขที่งาน')}</th><td id="rv-job">${esc(Mt.job || '')}</td></tr><tr><th>${T('Bridge', 'สะพาน')}</th><td>${esc(B.no)} · <span id="rv-ref">${esc(Mt.ref || '')}</span></td><th>${T('Date', 'วันที่')}</th><td>${today()}</td></tr><tr><th>${T('Assessed', 'ประเมิน')}</th><td id="rv-by">${esc(Mt.by || B.designer || '')}</td><th>${T('Checked', 'ตรวจสอบ')}</th><td id="rv-checked">${esc(Mt.checked || '')}</td></tr></table></header>
          ${html}<p class="rp-foot"><b>${COPY}</b> · ${T('Generated by StructCap. Units kN, kNm, m, mm, MPa, t. The engineer remains responsible for the inspection data, the model and the interpretation of results.', 'จัดทำโดย StructCap วิศวกรต้องรับผิดชอบต่อข้อมูลการตรวจสอบ แบบจำลอง และการตีความผลลัพธ์')}</p></article>`;
      S.reportOpen = true; const w = $('#reportWrap'); if (w) w.scrollIntoView({ behavior: 'smooth' });
    }

    // ------------------------------------------------------------------ events
    function cmd(c, v) {
      const B = A.B;
      if (c === 'new') { if (!confirm(T('Start a new bridge? The current data is replaced (Undo brings it back).', 'เริ่มสะพานใหม่? ข้อมูลปัจจุบันจะถูกแทนที่'))) return; snap(); A.B = TB.newBridge(); A.R = null; A.stale = true; A.sel = 'bridge'; persist(); render(); return; }
      if (c === 'ex') { snap(); A.B = TB.example3393(); A.R = null; A.stale = true; A.sel = 'bridge'; persist(); render(); toast(T('Bridge 3393 from the TIMBAR manual loaded (span 3, pier 2, abutment 2 as published).', 'โหลดสะพาน 3393 จากคู่มือ TIMBAR แล้ว'), 'ok'); return; }
      if (c === 'save') { persist(); saveFile(((B.no || 'bridge') + '_timber-rating.json').replace(/[^\w\-.]+/g, '_'), new Blob([JSON.stringify({ app: 'StructCap Timber', v: 1, B }, null, 1)], { type: 'application/json' })); return; }
      if (c === 'undo') { undo(false); return; } if (c === 'redo') { undo(true); return; }
      if (c === 'run') { run(); return; }
      if (c === 'report') { renderReport(); return; }
      if (c === 'draw') { ctx.go('tdraw'); return; }
      if (c === 'sel') { A.sel = v; refresh(); return; }
      if (c === 'drawall') { const R = A.R; if (!R) return; const seen = new Set(), list = []; R.summary.low.forEach(l => { const fm = /stringer/i.test(l.comp) ? 'stringer' : /halfcap bearing/i.test(l.comp) ? 'bearing' : /halfcap/i.test(l.comp) ? 'halfcap' : /Abutment.*pile/i.test(l.comp) ? 'abutPile' : /pile/i.test(l.comp) ? 'pierPile' : /planks/i.test(l.comp) ? 'planks' : null; const id = fm && G.TDET.SUGGEST[fm][0]; if (id && !seen.has(id)) { seen.add(id); list.push({ det: id, params: repairParams(id, l.comp), bridge: B.no }); } }); if (!list.length) { toast(T('Nothing below 100 % — no repairs suggested.', 'ไม่มีชิ้นส่วนต่ำกว่า 100 %'), ''); return; } queueRepairs(list); ctx.go('tdraw'); return; }
      snap();
      if (c === 'strn') { const [i, d] = v.split(':').map(Number); setStringers(i, B.spans[i].stringers.length + d); }
      else if (c === 'copyspan') { const i = +v, src = B.spans[i]; B.spans.forEach((S, j) => { if (j !== i) { const L = S.L, Lo = S.Lo, rate = S.rate; B.spans[j] = JSON.parse(JSON.stringify(src)); Object.assign(B.spans[j], { L, Lo, rate }); B.spans[j].patches.forEach(p => { p.lx = L; }); } }); }
      else if (c === 'patchadd') { const S = B.spans[+v]; (S.patches = S.patches || []).push({ name: T('Patch', 'แผ่น') + ' ' + (S.patches.length + 1), gamma: 22, x: 0, y: 0, lx: +S.L, ly: 1, t: [0.05, 0.05, 0.05, 0.05] }); }
      else if (c === 'patchdel') { const [i, j] = v.split(':').map(Number); B.spans[i].patches.splice(j, 1); }
      else if (c === 'kerbcalc') { const S = B.spans[+v], kw = +(prompt(T('Kerb width (m)', 'ความกว้างขอบทาง (ม.)'), '0.15') || 0), kh = +(prompt(T('Kerb height (m)', 'ความสูงขอบทาง (ม.)'), '0.30') || 0), rail = +(prompt(T('Guardrail line load (kN/m)', 'น้ำหนักราวกั้น (kN/m)'), '0.3') || 0); if (kw > 0) { const t = (rail + kw * kh * 10.8) / 10.8 / kw; (S.patches = S.patches || []).push({ name: 'Kerb + guardrail L', gamma: 10.8, x: 0, y: 0, lx: +S.L, ly: kw, t: [t, t, t, t] }, { name: 'Kerb + guardrail R', gamma: 10.8, x: 0, y: (+S.width || 7) - kw, lx: +S.L, ly: kw, t: [t, t, t, t] }); toast(T('Effective kerb thickness ', 'ความหนาขอบทางประสิทธิผล ') + f(t, 3) + ' m', 'ok'); } }
      else if (c === 'pileadd') { const Su = B.supports[+v], last = (Su.piles || [])[Su.piles.length - 1]; (Su.piles = Su.piles || []).push(last ? Object.assign(JSON.parse(JSON.stringify(last)), { x: +last.x + 2, id: (+last.id || Su.piles.length) + 1 }) : { x: 0.5, d: 380, def: 0, cond: 'G', grade: 'F17', Hgl: 1.2, dfix: 1, e: 0.15, dc: 1 }); }
      else if (c === 'piledel') { const [k, j] = v.split(':').map(Number); B.supports[k].piles.splice(j, 1); }
      else if (c === 'wadd') { const Su = B.supports[+v]; (Su.wing = Su.wing || []).push({ name: T('Wing wall ', 'กำแพงปีก ') + (Su.wing.length + 1), phi: 30, alpha: 45, slope: 2, passive: false, osw: 0.5, piles: [{ id: 1, h: 1.5, s: 0.7, d: 350, def: 0, cond: 'G', dc: 1 }] }); }
      else if (c === 'wdel') { const [k, w] = v.split(':').map(Number); B.supports[k].wing.splice(w, 1); }
      else if (c === 'wpadd') { const [k, w] = v.split(':').map(Number), P = B.supports[k].wing[w].piles; P.push(Object.assign({}, P[P.length - 1] || { h: 1, s: 1.5, d: 350 }, { id: P.length + 1 })); }
      else if (c === 'wpdel') { const [k, w, j] = v.split(':').map(Number); B.supports[k].wing[w].piles.splice(j, 1); }
      A.stale = true; persist(); refresh();
    }
    function onClick(a, b) {
      if (a === 'tb-rb') { cmd(b.dataset.c, b.dataset.v); return true; }
      if (a === 'tb-ribtab') { A.rib = b.dataset.t; ribRefresh(); return true; }
      if (a === 'tb-sel') { A.sel = b.dataset.k; refresh(); return true; }
      if (a === 'tb-tog') { A.open[b.dataset.k] = !A.open[b.dataset.k]; refresh(false); return true; }
      if (a === 'tb-rep') { queueRepairs([{ det: b.dataset.v, params: repairParams(b.dataset.v, b.dataset.c), bridge: A.B.no }]); ctx.go('tdraw'); return true; }
      return false;
    }
    function onInput(t) {
      if (!t.closest('.tb-app')) return false;
      if (!A._ts || Date.now() - A._ts > 800) snap(); A._ts = Date.now();
      if (t.dataset.tbspans) { setSpans(+t.value || 1); A.stale = true; persist(); refresh(false); return true; }
      if (t.dataset.tbveh) { const id = t.dataset.tbveh, q = TB.vehicle(id), V = A.B.veh = A.B.veh || {}, lst = q && q.opt ? (V.on = V.on || []) : (V.off = V.off || []), i = lst.indexOf(id), want = q && q.opt ? t.checked : !t.checked; if (want && i < 0) lst.push(id); else if (!want && i >= 0) lst.splice(i, 1); A.stale = true; persist(); refresh(false); return true; }
      const p = t.dataset.tb; if (!p) return true;
      const v = t.dataset.chk ? t.checked : t.dataset.num ? (t.value === '' ? '' : +t.value) : t.value; setPath(p, v); A.stale = true; persist();
      // live section properties on the stringer grid
      const m = /^spans\.(\d+)\.stringers\.(\d+)\.(e1|mid|e2)\./.exec(p);
      if (m) { try { const sec = TB.stringerSection(getPath('spans.' + m[1] + '.stringers.' + m[2] + '.' + m[3]), m[3] !== 'mid'), id = m[1] + '-' + m[2] + '-' + m[3], a = $('#tbA-' + id), i = $('#tbI-' + id), y = $('#tbY-' + id); if (a) a.textContent = f(m[3] === 'mid' ? sec.Ag / 1e5 : sec.A / 1e5, 3); if (i) i.textContent = f(sec.I / 1e9, 3); if (y && m[3] === 'mid') y.textContent = f(sec.ymax, 1); } catch (e) { } }
      if (t.tagName === 'SELECT' && (/\.(mat|def)$/.test(p))) { const pan = $('#tbPanel'), sc = pan && pan.scrollTop; refresh(); const pn = $('#tbPanel'); if (pn) pn.scrollTop = sc; }
      else { const tr = $('#tbTree'); if (tr) tr.innerHTML = treeHTML(); const s = $('#tbSch'); if (s) s.innerHTML = schematic(); }
      return true;
    }
    let bound = false;
    function mount() {
      if (bound) return; bound = true;
      document.addEventListener('change', e => { const t = e.target; if (S.view !== VIEW || !t || t.id !== 'tb-file') return; const fl = t.files[0]; if (!fl) return; fl.text().then(txt => { try { const j = JSON.parse(txt), B = j.B || j; if (!B.spans || !B.supports) throw 0; snap(); A.B = B; A.R = null; A.stale = true; A.sel = 'bridge'; persist(); render(); toast(T('Bridge opened', 'เปิดสะพานแล้ว'), 'ok'); } catch (er) { toast(T('That file is not a StructCap timber bridge.', 'ไฟล์นี้ไม่ใช่ไฟล์สะพานไม้ StructCap'), 'bad'); } }); });
      document.addEventListener('keydown', e => { if (S.view !== VIEW) return; const tg = e.target; if (tg && /INPUT|SELECT|TEXTAREA/.test(tg.tagName)) return; if ((e.ctrlKey || e.metaKey) && e.key === 'Enter') { e.preventDefault(); run(); } else if ((e.ctrlKey || e.metaKey) && (e.key === 'z' || e.key === 'Z')) { e.preventDefault(); undo(e.shiftKey); } });
    }
    return { view, mount, onClick, onInput, state: A, run, renderReport };
  };
})(typeof window !== 'undefined' ? window : globalThis);
